---
title: "Pairwise Detection Figure"
output: html_document
date: "2024-01-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(grid)
require(dplyr)
require(gridExtra)
require(ggpubr)
```

```{r}
select <- dplyr::select; mutate <- dplyr::mutate; arrange=dplyr::arrange

dset.ord.site <- readRDS("../data/corr_fmri_metadata.rds")

results <- readRDS("../data/pairwise.rds") %>%
  ungroup() %>%
  mutate(p.value=p.adjust(p.value, method="BH"),
         Dataset.Trt=factor(Dataset.Trt, 
                            levels=dset.ord.site$Dataset, 
                            ordered=TRUE),
         Dataset.Ctrl=factor(Dataset.Ctrl, 
                             levels=dset.ord.site$Dataset, 
                             ordered=TRUE)) %>%
  mutate(Method=factor(Method, levels=c("Associational", "Conditional (Non-Causal)", "Adjusted (Causal)", "Crossover"), ordered=TRUE))

color.spec <- c("Adjusted (Causal)"="cornflowerblue", "Crossover"="purple", "Conditional (Non-Causal)"="orange","Associational"="red")
```

```{r}
reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}
pval_hmap_chart <- function(data, categories=c("Conditional (Non-Causal)", "Adjusted (Causal)"), category.ref="Adjusted (Causal)",
                            dset.ord.site, title="", alpha=.05, method="Raw", text.size=15, preproc=TRUE) {
  
  dset.ord.trt <- dset.ord.site %>%
     rename(n.trt=n, Dataset.Trt= Dataset, id.trt=id) %>%
     select(n.trt, Dataset.Trt, id.trt)
  dset.ord.ctrl <- dset.ord.site %>%
     rename(n.ctrl=n, Dataset.Ctrl= Dataset, id.ctrl=id) %>%
     select(n.ctrl, Dataset.Ctrl, id.ctrl)

  data.aug <- data %>%
    filter(Method %in% categories) %>%
    left_join(dset.ord.trt) %>%
    left_join(dset.ord.ctrl) %>%
    ungroup() %>%
    mutate(id.row=row_number()) %>%
    group_by(id.row) %>%
    mutate(Dataset.Trt.X=c(Dataset.Trt, Dataset.Ctrl)[which.min(c(id.trt, id.ctrl))],
           Dataset.Ctrl.X=c(Dataset.Trt, Dataset.Ctrl)[which.max(c(id.trt, id.ctrl))],
           Dataset.Trt=Dataset.Trt.X, Dataset.Ctrl=Dataset.Ctrl.X,
           Dataset.tmp=as.character(Dataset.Trt),
           Dataset.Trt=ifelse(category.ref == Method, as.character(Dataset.Ctrl), as.character(Dataset.Trt)),
           Dataset.Ctrl=ifelse(category.ref == Method, as.character(Dataset.tmp), as.character(Dataset.Ctrl)),
           Dataset.Trt=factor(Dataset.Trt,
                              levels=dset.ord.site$Dataset,
                              ordered=TRUE),
           Dataset.Ctrl=factor(Dataset.Ctrl,
                               levels=dset.ord.site$Dataset,
                               ordered=TRUE))
  
  sig.dat <- data.aug %>% filter(!is.na(p.value)) %>% filter(p.value < alpha)
  failed.dat <- data.aug %>% filter(is.na(p.value))
  
  data.aug %>%
    filter(!is.na(p.value)) %>%
    ggplot(aes(x=Dataset.Trt, y=Dataset.Ctrl, alpha=p.value)) +
    geom_tile(aes(fill=Method)) +
    xlab("Dataset") +
    ylab("Dataset") +
    scale_alpha_continuous(trans=reverselog_trans(10), limits=c(1, .0004), breaks=c(.001, .01, .1, 1), 
                           labels=c(".001", ".01", ".1", "1"), name="p-value") +
    scale_fill_manual(values=color.spec,  name="Estimated Effect") +
    scale_x_discrete(drop=FALSE) +
    scale_y_discrete(drop=FALSE) +
    geom_text(data=sig.dat, label="\u2713", color='black',
              family="Arial Unicode MS", alpha=1) +
    geom_text(data=failed.dat, label="\u2717", color='red',
              family="Arial Unicode MS", alpha=1) +
    ggtitle(title) +
    theme_bw() +
    theme(text=element_text(size=text.size), axis.text.x=element_text(angle=90, hjust = 0.95, vjust=.2),
          panel.grid.major=element_blank(),
          panel.grid.minor = element_blank(),
          legend.position="bottom", legend.direction="horizontal", legend.box="vertical")
}
```

```{r, fig.height=7, fig.width=13}
plt.caus <- pval_hmap_chart(results, dset.ord.site, categories=c("Adjusted (Causal)", "Conditional (Non-Causal)"),
                            category.ref="Adjusted (Causal)", title="B Demographic-Adjusted Effects")
plt.noncaus <- pval_hmap_chart(results, dset.ord.site, categories=c("Associational", "Crossover"),
                               category.ref="Crossover", title="A Effects without demographic adjustment")

plt.comb <- arrangeGrob(plt.noncaus, plt.caus, ncol=2)
plot(plt.comb)
```


## Figure revision (for draft)

```{r, fig.height=7, fig.width=13}
pval.cond_vs_adj <- pval_hmap_chart(results, dset.ord.site, categories=c("Conditional (Non-Causal)", "Adjusted (Causal)"),
                                    category.ref="Adjusted (Causal)", title="A. Comparing Conditional and Causal Approaches for \nBatch Effect Detection")

scanner.info <- dset.ord.site %>% 
  select(Dataset, "Scan.Manuf", "Scan.Model") %>%
  mutate("Scanner" = paste(Scan.Manuf, Scan.Model)) %>%
  select(-Scan.Manuf, -Scan.Model) %>%
  left_join(dset.ord, by=c("Dataset"="Dataset"))

results.scanner <- results %>%
  left_join(scanner.info %>% rename(Scanner.Trt=Scanner, Continent.Trt=Continent),
            by=c("Dataset.Trt"="Dataset")) %>%
  left_join(scanner.info %>% rename(Scanner.Ctrl=Scanner, Continent.Ctrl=Continent),
            by=c("Dataset.Ctrl"="Dataset")) %>%
  mutate(Same.Scanner = Scanner.Trt == Scanner.Ctrl, Same.Cont=Continent.Trt == Continent.Ctrl)

pval.hists <- results.scanner %>%
  filter(Method %in% c("Conditional (Non-Causal)", "Adjusted (Causal)")) %>%
  ungroup() %>%
  mutate(Scanner.Rel=ifelse(Same.Scanner, "Same Scanner", "Different Scanner")) %>%
  mutate(Overlap.Group=ifelse(!Same.Cont, "Low Overlap, Different Continent", ifelse(Overlap > .05, "High Overlap, Same Continent", "Low Overlap, Same Continent"))) %>%
  group_by(Method, Scanner.Rel, Overlap.Group) %>%
  summarize(`Confounded`=sum(is.na(p.value))/n(), Reject=sum(p.value < .05, na.rm=TRUE)/n(), 
            `Fail to reject`=sum(p.value > .05, na.rm=TRUE)/n()) %>%
  pivot_longer(`Confounded`:`Fail to reject`, values_to="Fraction", names_to="Test Outcome") %>%
  mutate(`Test Outcome`=factor(`Test Outcome`, levels=c("Reject", "Fail to reject", "Confounded"),
                               ordered=TRUE)) %>%
  mutate(`Overlap.Group`=factor(`Overlap.Group`, levels=c("High Overlap, Same Continent", "Low Overlap, Same Continent", "Low Overlap, Different Continent"),
                                ordered=TRUE)) %>%
  filter(!is.na(Scanner.Rel)) %>%
  ggplot(aes(x=`Test Outcome`, y=Fraction, fill=Method, color=Method)) +
  geom_col(position="dodge") +
    scale_fill_manual(values=color.spec, name="Estimated Effect") +
    scale_color_manual(values=color.spec, name="Estimated Effect") +
  facet_grid(Overlap.Group ~ Scanner.Rel) +
  theme_bw() +
  theme(text=element_text(size=15)) +
  geom_vline(xintercept = .05, linetype="dashed") +
  guides(fill=FALSE, shape=FALSE, color=FALSE, size=FALSE, scale="none") +
  ggtitle("B. Batch Effect Detectability (by Overlap)")

plt.cond_vs_adj = ggarrange(pval.cond_vs_adj, pval.hists, nrow=1, widths=c(1.5, 1.1))
ggsave('./Figures/cond_vs_adj_detection_raw.svg', plot=plt.cond_vs_adj, width=11, height=7.5)
```


```{r}
 results.scanner %>%
     filter(Data %in% c("Conditional (Non-Causal)", "Adjusted (Causal)")) %>%
     ungroup() %>%
     mutate(Scanner.Rel=ifelse(Same.Scanner, "Same Scanner", "Different Scanner")) %>%
     mutate(Overlap.Group=ifelse(!Same.Cont, "Low Overlap, Different Continent", ifelse(Overlap > .05, "High Overlap, Same Continent", "Low Overlap, Same Continent"))) %>%
     group_by(Method, Scanner.Rel, Overlap.Group) %>%
 summarize(Count=n())

results %>%
  filter(Method %in% c("Conditional (Non-Causal)", "Adjusted (Causal)")) %>%
  mutate(test=p.value <= .05) %>%
  select(Method, test) %>%
  group_by(Method) %>%
  summarize(posrate = mean(test, na.rm=TRUE), n.na=sum(is.na(test)), 
            npos=sum(test, na.rm=TRUE), nneg = sum(test == 0, na.rm=TRUE), ntot=n())
```

```{r}
pval.ass_vs_cross <- pval_hmap_chart(results, dset.ord.site, categories=c("Associational", "Crossover"),
                                    category.ref="Crossover", title="A. Comparing Associational and Crossover Effects for \nBatch Effect Detection")

results.scanner <- results %>%
  left_join(scanner.info %>% rename(Scanner.Trt=Scanner, Continent.Trt=Continent),
            by=c("Dataset.Trt"="Dataset")) %>%
  left_join(scanner.info %>% rename(Scanner.Ctrl=Scanner, Continent.Ctrl=Continent),
            by=c("Dataset.Ctrl"="Dataset")) %>%
  mutate(Same.Scanner = Scanner.Trt == Scanner.Ctrl, Same.Cont=Continent.Trt == Continent.Ctrl)

pval.hists <- results.scanner %>%
  filter(Method %in% c("Associational", "Crossover")) %>%
  ungroup() %>%
  mutate(Scanner.Rel=ifelse(Same.Scanner, "Same Scanner", "Different Scanner")) %>%
  mutate(Overlap.Group=ifelse(!Same.Cont, "Low Overlap, Different Continent", ifelse(Overlap > .05, "High Overlap, Same Continent", "Low Overlap, Same Continent"))) %>%
  group_by(Method, Scanner.Rel, Overlap.Group) %>%
  summarize(`Confounded`=sum(is.na(p.value))/n(), Reject=sum(p.value < .05, na.rm=TRUE)/n(), 
            `Fail to reject`=sum(p.value > .05, na.rm=TRUE)/n()) %>%
  pivot_longer(`Confounded`:`Fail to reject`, values_to="Fraction", names_to="Test Outcome") %>%
  mutate(`Test Outcome`=factor(`Test Outcome`, levels=c("Reject", "Fail to reject", "Confounded"),
                               ordered=TRUE)) %>%
  mutate(`Overlap.Group`=factor(`Overlap.Group`, levels=c("High Overlap, Same Continent", "Low Overlap, Same Continent", "Low Overlap, Different Continent"),
                                ordered=TRUE)) %>%
  filter(!is.na(Scanner.Rel)) %>%
  ggplot(aes(x=`Test Outcome`, y=Fraction, fill=Method, color=Method)) +
  geom_col(position="dodge") +
    scale_fill_manual(values=color.spec, name="Estimated Effect") +
    scale_color_manual(values=color.spec, name="Estimated Effect") +
  facet_grid(Overlap.Group ~ Scanner.Rel) +
  theme_bw() +
  theme(text=element_text(size=15)) +
  geom_vline(xintercept = .05, linetype="dashed") +
  guides(fill=FALSE, shape=FALSE, color=FALSE, size=FALSE, scale="none") +
  ggtitle("B. Batch Effect Detectability (by Overlap)")

plt.ass_vs_ccross = ggarrange(pval.ass_vs_cross, pval.hists, nrow=1, widths=c(1.5, 1.1))
ggsave('./Figures/ass_vs_ccross_detection_raw.svg', plot=plt.ass_vs_ccross, width=11, height=7.5)
```


```{r}
 results.scanner %>%
     filter(Method %in% c("Associational", "Crossover")) %>%
     ungroup() %>%
     mutate(Scanner.Rel=ifelse(Same.Scanner, "Same Scanner", "Different Scanner")) %>%
     mutate(Overlap.Group=ifelse(!Same.Cont, "Low Overlap, Different Continent", ifelse(Overlap > .05, "High Overlap, Same Continent", "Low Overlap, Same Continent"))) %>%
     group_by(Data, Scanner.Rel, Overlap.Group) %>%
 summarize(Count=n())

results$Site %>%
  filter(Method %in% c("Associational", "Crossover")) %>%
  mutate(test=p.value <= .05) %>%
  select(Data, test) %>%
  group_by(Data) %>%
  summarize(posrate = mean(test, na.rm=TRUE), n.na=sum(is.na(test)), 
            npos=sum(test, na.rm=TRUE), nneg = sum(test == 0, na.rm=TRUE), ntot=n())
```

