---
title: "Figure 0 Sims V2"
output: html_document
date: "2023-10-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
require(causalBatch)
require(tidyverse)
require(parallel)
require(dplyr)
source("../utilities/combat_gam.R")
source("../utilities/combat_return.R")
source("../utilities/sim_helpers.R")
batch.cols <- c("0"="#d95f02", "1"="#7570b3")
```

```{r}
n = 500
overlap.settings <- list("I. Moderate Overlap, Overcorrection"=list(n=n, unbalancedness=3, eff_sz=0.5,
                                                     a=-1, b=12, err=1/8),
                         "II. Moderate Overlap, Undercorrection"=list(n=n, unbalancedness=3, eff_sz=-0.5,
                                                     a=-1, b=12, err=1/8))
sig.sims <- gen.simulations(cb.sims.sim_sigmoid, overlap.settings)

sig.true_list <- get.true_signal(sig.sims)
sig.true_df <- get.true_signal_df(sig.true_list)

ccombat.fit <- fit.cComBat(sig.sims)
matching_combat.fit <- fit.matching_cComBat(sig.sims)
ccombat.applied <- apply.cComBat(sig.sims, ccombat.fit)
matching_combat.applied <- apply.cComBat(sig.sims, matching_combat.fit)

sig.cc_true_adj <- apply.cComBat(sig.true_list, ccombat.fit)
sig.matching.cc_true_adj <- apply.cComBat(sig.true_list, matching_combat.fit)

ccombat.covar <- covar.cmp_to_oracle(ccombat.fit, sig.sims, matching_combat.fit)
matching_combat.covar <- covar.cmp_to_oracle(matching_combat.fit, sig.sims, matching_combat.fit)
```

```{r}
raw.dat <- do.call(rbind, lapply(names(sig.sims), function(x) {
  dat = sig.sims[[x]]
  return(data.frame(X=dat$Xs, Batch=dat$Ts, Y=dat$Ys[,1], Setting=x, Overlap=dat$Overlap, Signal="Raw"))
}))
points <- do.call(rbind, list(raw.dat %>% mutate(Algorithm="Raw"),
                    ccombat.applied %>% mutate(Algorithm="cComBat"),
                    matching_combat.applied %>% mutate(Algorithm="Matching cComBat"))) %>%
  mutate(Algorithm=factor(Algorithm, levels=c("Raw", "cComBat", "Matching cComBat"), ordered=TRUE))

lines <- do.call(rbind, list(
  sig.true_df %>% mutate(Algorithm="Raw"),
  sig.cc_true_adj %>% mutate(Algorithm="cComBat"),
  sig.matching.cc_true_adj %>% mutate(Algorithm="Matching cComBat")
)) %>%
  mutate(Algorithm=factor(Algorithm, levels=c("Raw", "cComBat", "Matching cComBat"), ordered=TRUE))

batch.dif <- lines %>%
  pivot_wider(names_from=Batch, values_from=Y) %>%
  group_by(X, Setting, Overlap, Algorithm) %>%
  mutate(ymin=min(`0`, `1`), ymax=max(`0`, `1`))

ggplot(points) +
  geom_ribbon(data=batch.dif, aes(x=X, ymin=ymin, ymax=ymax), alpha=0.3, fill="red") +
  geom_point(aes(x=X, y=Y, color=factor(Batch)), size=0.5, alpha=.5) +
  geom_line(data=lines, aes(x=X, y=Y, color=factor(Batch)), size=1) +
  scale_color_manual(values = batch.cols, name="Batch") +
  facet_grid(Setting~Algorithm) +
  theme_bw() +
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        strip.background=element_blank(), text=element_text(size=13),
        axis.text.y=element_blank(), axis.ticks.y=element_blank())
```

```{r}
R <- 100
eff_sz.settings <- c("negative"=-1, "null"=0)
betas <- seq(1, 4, length.out=11)
n <- 1000
```

```{r}
settings <- list(
  "No Batch Effect"=list(n=n, eff_sz=0),
  "Batch Effect"=list(n=n, eff_sz=1)
)
lin.sims <- gen.simulations(cb.sims.sim_linear, settings)
lin.true_list <- get.true_signal(lin.sims)
lin.true_df <- get.true_signal_df(lin.true_list)

sig.sims <- gen.simulations(cb.sims.sim_sigmoid, settings)
sig.true_list <- get.true_signal(sig.sims)
sig.true_df <- get.true_signal_df(sig.true_list)

nm.sims <- gen.simulations(cb.sims.sim_impulse_asycov, settings)
nm.true_list <- get.true_signal(nm.sims)
nm.true_df <- get.true_signal_df(nm.true_list)

true_sig <- rbind(lin.true_df %>% mutate(Context="Linear"),
                  sig.true_df %>% mutate(Context="Non-Linear"),
                  nm.true_df %>% mutate(Context="Non-Monotone")) %>%
  mutate(Batch=factor(Batch), 
         Context=factor(Context, levels=c("Linear", "Non-Linear", "Non-Monotone"),
                        ordered=TRUE),
         Setting=factor(Setting, levels=c("Batch Effect", "No Batch Effect", ordered=TRUE)))

ggplot(true_sig, aes(x=X, y=Y, color=Batch)) +
  geom_line(linewidth=1.2) +
  scale_color_manual(values=batch.cols) +
  facet_grid(Setting ~ Context) +
  theme_bw() +
  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
          strip.background=element_blank(), text=element_text(size=10))
```

```{r, eval=FALSE}
sim_results <- do.call(rbind, lapply(names(eff_sz.settings), function(j) {
  eff_sz=eff_sz.settings[[j]]
  print(j)
  sim.cate.settings <- lapply(1:length(betas), function(i) {
    list(alpha=2, n=n, unbalancedness=betas[i], eff_sz=eff_sz)
  })
  names(sim.cate.settings) <- as.character(1:length(betas))
  
  sig.cate <- compute.mean_CATE(cb.sims.sim_sigmoid, paramlist=sim.cate.settings,
                                R=R, fname=NULL) %>% #sprintf("sim_outs/sigmoid_%s", j)) %>%
    mutate(Experiment="Non-Linearity")
  linear.cate <- compute.mean_CATE(cb.sims.sim_linear, paramlist=sim.cate.settings,
                                R=R, fname=NULL) %>% #sprintf("sim_outs/line_%s", j)) %>%
    mutate(Experiment="Linear")
  imp.cate <- compute.mean_CATE(cb.sims.sim_impulse, paramlist=sim.cate.settings,
                                R=R, fname=NULL) %>%#sprintf("sim_outs/imp_%s", j)) %>%
    mutate(Experiment="Non-Monotone")
  
  return(rbind(sig.cate, linear.cate, imp.cate) %>% mutate(True.Effect=eff_sz))
}))
saveRDS(sim_results, "../data/simulations.rds")
```

```{r}
sim_results <- (dat=readRDS("../data/simulations.rds")) %>%
  group_by(Setting, Strategy, Effect, Overlap, Experiment, True.Effect) %>%
  summarize(N = sum(!is.na(Statistic)), Mean=mean(abs(Statistic), na.rm=TRUE),
            SE = sd(Statistic, na.rm=TRUE)/sqrt(N),
            lpt = quantile(abs(Statistic), probs=0.1, na.rm=TRUE),
            upt = quantile(abs(Statistic), probs=0.9, na.rm=TRUE),
            nfail = sum(is.na(Statistic))) %>%
  mutate(Experiment = factor(Experiment, ordered=TRUE, levels=c("Linear", "Non-Linearity", "Non-Monotone"))) %>%
  filter(Overlap > .01)

hline.dat <- do.call(rbind, lapply(eff_sz.settings, function(eff_sz) {
  return(data.frame(True.Effect=eff_sz, Experiment=c("Linear", "Non-Linearity", "Non-Monotone")))
}))
```

```{r}
library("scales")
reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}

ggplot(data=sim_results %>% filter(Effect == "Batch"), aes(x=Overlap, y=Mean)) +
    geom_line(data=sim_results %>% filter(Effect == "Batch"), aes(color=Strategy), linetype="dotted") +
    geom_line(data=sim_results %>% filter(Effect == "Batch", nfail <= R/2),
              aes(color=Strategy)) +
    scale_color_manual(values=c("cComBat"="#dd00dd", "cComBat-GAM"="#770077", "AIPW cComBat"="green", "Matching cComBat"="blue", "Oracle"="red")) +
    scale_linetype_manual(values=c("cComBat"="solid", "cComBat-GAM"="solid", "AIPW cComBat"="solid", "Matching cComBat"="solid")) +
    geom_hline(data=hline.dat, aes(yintercept=abs(True.Effect)), color="black", linetype="dashed") +
    geom_hline(aes(yintercept=0), color="black", linetype="dotted") +
    scale_x_continuous(name="Covariate Overlap", trans=reverselog_trans(2), 
                       breaks=c(0.02, 0.1, 0.3, 1)) +
    scale_y_continuous(name="AATE", limits=c(0, 2), expand=c(0, 0)) +
    theme_bw() +
    ggtitle("Performance of batch effect correction techniques on simulated data") +
    facet_grid(True.Effect ~ Experiment) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
          strip.background=element_blank(), text=element_text(size=13))
```

```{r}
ggplot(data=sim_results %>% filter(Effect == "Covariate"), aes(x=Overlap, y=Mean)) +
    geom_line(data=sim_results %>% filter(Effect == "Covariate"), aes(color=Strategy), linetype="dotted") +
    geom_line(data=sim_results %>% filter(Effect == "Covariate", nfail <= R/2),
              aes(color=Strategy)) +
    scale_color_manual(values=c("cComBat"="#dd00dd", "cComBat-GAM"="#770077", "AIPW cComBat"="green", "Matching cComBat"="blue", "Oracle"="red")) +
    geom_hline(data=hline.dat, aes(yintercept=abs(True.Effect)), color="black", linetype="dashed") +
    geom_hline(aes(yintercept=0), color="black", linetype="dotted") +
    scale_x_continuous(name="Covariate Overlap", trans=reverselog_trans(2), 
                       breaks=c(0.02, 0.1, 0.3, 1)) +
    scale_y_continuous(name="Correlation(Corrected Data, Covariate Effect)", limits=c(0, 1), expand=c(0, 0)) +
    theme_bw() +
    ggtitle("Performance of batch effect correction techniques on simulated data") +
    facet_grid(True.Effect ~ Experiment) +
    theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
          strip.background=element_blank(), text=element_text(size=13))
```

