---
title: "edgewise_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(ggplot2)
require(energy)
require(parallel)
require(tidyverse)
require(mltools)
require(grid)
require(gridExtra)
ncores <- parallel::detectCores() - 1

alpha = .05
```


```{r}
meth.ord <- c("Raw", "ComBat", "cComBat", "cComBat-GAM", "Matching cComBat")
row.ord <- c("American Clique", "All")
outputs <- readRDS('../data/subseq.rds') %>%
  ungroup() %>%
  mutate(p.value=p.adjust(p.value, method="BH")) %>%
  group_by(Method, Cohort) %>%
  arrange(p.value, desc(Statistic)) %>%
  mutate(Rank=row_number()) %>%
  mutate(Method=factor(Method, levels=meth.ord, ordered = TRUE),
         Cohort=factor(Cohort, levels=row.ord, ordered=TRUE)) %>%
  ungroup()
```

```{r}
dice <- function(a, b) {
  length(intersect(a, b))/length(union(a, b))
}

overlap_dice <- function(X) {
  methods = unique(X$Method)
  Dice=sapply(unique(X$Method), function(meth1) {
    sapply(unique(X$Method), function(meth2) {
      suppressMessages(
        dice((X %>% filter(Method == meth1) %>% ungroup())$Edge, 
             (X %>% filter(Method == meth2) %>% ungroup())$Edge))
    })
  })
  colnames(Dice) <- rownames(Dice) <- unique(X$Method)
  data.frame(Method1=colnames(Dice)[col(Dice)], Method2=rownames(Dice)[row(Dice)],
             DICE=c(Dice)) %>%
    mutate(Method1=factor(Method1, levels=meth.ord, ordered=TRUE),
           Method2=factor(Method2, levels=meth.ord, ordered=TRUE)) %>%
    arrange(Method1, Method2)
}

n.rank <- 100
dice.mtx.lng <- outputs %>%
  filter(Cohort == "American Clique") %>%
  filter(Rank <= n.rank) %>%
  overlap_dice()

dice.plt <- dice.mtx.lng %>%
  filter(Method1 != Method2) %>%
  ggplot(aes(x=Method1, y=Method2, fill=DICE)) +
    geom_tile() +
    scale_fill_gradient(low="white", high="darkgreen", limits=c(0, 1)) +
    xlab("Method") +
    ylab("Method") +
    ggtitle(sprintf("(B) DICE Overlap of Top %d Edges", n.rank)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          panel.grid=element_blank(), strip.text=element_text(size=14), strip.background = element_blank())
```


```{r}
plt.sig <- outputs %>%
  rbind(outputs %>%
          mutate(Row.Tmp=Row, Row = Column, Column=Row.Tmp) %>% 
          select(-Row.Tmp)) %>%
  filter(p.value < alpha, Cohort == "American Clique") %>%
  filter(Method %in% c("Raw", "ComBat", "cComBat", "cComBat-GAM", "Matching cComBat")) %>%
  ggplot() +
  geom_tile(aes(x=Row, y=Column, alpha=rev(Rank), fill=Rank)) +
  scale_fill_gradient(name="Rank", low="#530481", high="#fdf2fe") +
  scale_alpha_continuous() +
  ggtitle("(A) Comparison of Significant Edges") +
  scale_x_discrete(breaks=c(1, 116), name="Parcel") +
  scale_y_discrete(breaks=c(1, 116), name="Parcel") +
  facet_grid(".~Method") +
  guides(alpha=FALSE) +
  theme_bw() +
  theme(panel.grid=element_blank(), strip.text=element_text(size=14), strip.background = element_blank())
```

```{r, fig.height=3.5, fig.width=18}
grid.arrange(plt.sig, dice.plt, nrow=1, widths=c(.65, .2))
```

### Preserving within-individual signal

```{r}
preproc.dat <- readRDS('../data/corrected_data.rds')

nroi <- 116

# Create the pairs in the upper-right quadrant for homotopic/non-homotopic edges
homotopic.edges <- cbind(seq(1, nroi-1, by=2), seq(2, nroi, by=2))
m_upper <- upper.tri(matrix(1, nroi, nroi), diag=FALSE)
m_upper[homotopic.edges] <- 0
nonhomotopic.edges <- which(m_upper == 1, arr.ind=TRUE)

# Left vs. Right hemisphere
odd_idx <- seq(1, nroi, by=2)
even_idx <- seq(2, nroi, by=2)
same.hem <- array(0, dim=c(nroi, nroi))
same.hem[odd_idx, odd_idx] <- 1; same.hem[even_idx, even_idx] <- 1
same.hem <- same.hem*upper.tri(same.hem, diag=FALSE)
homophilic.edges <- which(same.hem == 1, arr.ind=TRUE)

opp.hem <- array(0, dim=c(nroi, nroi))
opp.hem[odd_idx, even_idx] <- 1; opp.hem[even_idx, odd_idx] <- 1
opp.hem <- opp.hem*upper.tri(opp.hem, diag=FALSE)
heterophilic.edges <- which(opp.hem == 1, arr.ind=TRUE)
```

#### Connectome plots

```{r}
conn.dat <- do.call(rbind, lapply(names(preproc.dat), function(fn.name) {
  gr <- array(apply(preproc.dat[[fn.name]]$Ys, 2, mean), dim=c(nroi, nroi))
  gr %>%
    as.data.frame() %>%
    rownames_to_column("Parcel i") %>%
    pivot_longer(
      cols = -`Parcel i`,
      names_to = "Parcel j",
      values_to = "Edge Weight"
    ) %>%
    mutate(Method=fn.name, `Parcel i`=as.numeric(`Parcel i`),
           `Parcel j` = as.numeric(str_remove(`Parcel j`, "V")))
})) %>%
  mutate(Method=factor(Method, ordered=TRUE, levels=c("Raw", "ComBat", "cComBat", "cComBat-GAM", "Matching cComBat")))

conn.avg.plt <- ggplot(conn.dat, aes(x=`Parcel i`, y=`Parcel j`, fill=`Edge Weight`)) +
  geom_tile() +
  scale_fill_gradient(name="Edge Weight", high="#530481", low="#fdf2fe", limits=c(0, 1)) +
  scale_x_continuous(limits=c(1, 116), breaks=c(1, 58, 116), name="Parcel", expand = c(0, 0)) +
  scale_y_continuous(limits=c(1, 116), breaks=c(1, 58, 116), name="Parcel", expand = c(0, 0)) +
  facet_grid(.~Method) +
  theme_bw() +
  theme(panel.grid=element_blank(), strip.text=element_text(size=14), strip.background = element_blank()) +
  ggtitle("(A) Average connectome")
```

#### Effect size preservation

```{r}
# reorganize data into n x nroi x nroi array
results <- do.call(rbind, lapply(names(preproc.dat), function(strategy) {
  str.preproc.dat <- preproc.dat[[strategy]]
  n <- nrow(str.preproc.dat$Ys)
  
  preproc.gr.dat <- aperm(array(t(str.preproc.dat$Ys), dim=c(nroi, nroi, n)), c(3,1,2))
  do.call(rbind, lapply(1:n, function(i) {
    gr.sub <- preproc.gr.dat[i,,]
    homotopic.diff=mean(gr.sub[homotopic.edges]) - mean(gr.sub[nonhomotopic.edges])
    homophilic.diff=mean(gr.sub[homophilic.edges]) - mean(gr.sub[heterophilic.edges])
    
    
    return(data.frame(Subject=rownames(str.preproc.dat$Xs)[i], Homotopic.Difference=homotopic.diff,
                      Homophilic.Difference=homophilic.diff, Method=strategy))
  }))
}))
```

```{r, fig.height=3, fig.width=8}
results.matched.to.raw <- results %>%
  filter(Method != "Raw") %>%
  rename(Method.Homotopic.Difference=Homotopic.Difference, Method.Homophilic.Difference=Homophilic.Difference) %>%
  left_join(results %>%
              filter(Method == "Raw") %>%
              rename(Raw.Homotopic.Difference=Homotopic.Difference, 
                     Raw.Homophilic.Difference=Homophilic.Difference) %>%
              select(-Method),
            by=c("Subject"="Subject")) %>%
  pivot_longer(
    cols = contains("Difference"),
    names_to = c("Type", "Effect.Type"),
    names_pattern = "(Method|Raw)\\.(Homotopic|Homophilic)\\.Difference",
    values_to = "Difference"
  ) %>%
  pivot_wider(
    names_from = Type,
    names_glue = "{.value}_{Type}",
    values_from = Difference
  ) %>%
  rename(
    Method.Difference = Difference_Method,
    Raw.Difference = Difference_Raw
  )

sanity.check.plt <- ggplot(results.matched.to.raw %>% mutate(ord=runif(n())) %>% arrange(ord), aes(x=Raw.Difference, y=Method.Difference, color=Method)) +
  geom_point(alpha=0.4) +
  scale_color_manual(values=c("cComBat"="#dd00dd", "cComBat-GAM"="#770077", "ComBat"="black", "Matching cComBat"="blue")) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", linewidth=1.2) +
  facet_wrap(~Effect.Type, scales="free", nrow=1) +
  scale_x_continuous(name="Connectivity difference (Raw)") +
  scale_y_continuous(name="Connectivity difference (Method)") +
  theme_bw() +
  ggtitle("(B) Preservation of within-individual effects") +
  theme(panel.grid=element_blank(), strip.text=element_text(size=14), strip.background = element_blank())
```

```{r, fig.width=15, fig.height=7}
grid.arrange(conn.avg.plt, sanity.check.plt, nrow=2)
```